[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
version = "0.0.0"

[dependencies]
clap = {version = "3.0.0-rc.7", features = ["derive", "wrap_help"]}
itertools = "0.10"
nom = "7.1"
rustyline = "9.0"
strum = {version = "0.23", features = ["derive"]}
sysinfo = "0.22"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
criterion = "0.3"
proptest = "1.0"

[[bench]]
harness = false
name = "dummy_benchmark"
