[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
version = "0.0.0"
rust-version = "1.57.0"
# Reduce the package size by only including things necessary for building it.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/Cargo.lock",
    "LICENSE",
    "README.md",
]


[dependencies]
strum = { version = "0.23", features = ["derive"] }
clap = {version = "3.0.0", features = ["derive", "wrap_help"]}
itertools = "0.10"
rustyline = "9.0"
sysinfo = "0.22"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
criterion = "0.3"
iai = "0.1"

[[bench]]
harness = false
name = "perft"

# TODO: Mention this in BUILDING.md.
# TODO: Test this out once the benchmarks are available and tweak specific
# values.
[profile.fast]
inherits = "release"
# lto = "fat"
# codegen-units = 1
# target-cpu = "native" (https://github.com/kirillbobyrev/pabi/issues/17)
# tune-cpu = "native"
# TODO: Tweak inline-threshold.
# TODO: Set profile-generate and profile-use (https://github.com/kirillbobyrev/pabi/issues/9).
