[package]
name = "bibimbap"
version = "0.0.0"
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/bibimbap"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/bibimbap"
keywords = []
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/bibimbap"

[dependencies]
clap = "3.0.0-beta.5"
log = "0.4"

[dev-dependencies]
criterion = "0.3"
proptest = "1.0"

[[bench]]
harness = false
name = "dummy_benchmark"
