edition = "2021"
comment_width = 100
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
# TODO: license_template_path
