edition = "2018"
max_width = 100
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
newline_style = "Unix"
imports_layout = "HorizontalVertical"
# TODO: license_template_path
