name: Feature Request/Enhancement
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement or Feature you want propose.
    validations:
      required: true
