---
name: Build documentation
on: [push, pull_request]
jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build the docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
